spring:
  application:
    name: order-client
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring_cloud_mall?useSLL=false&characterEncoding=utf8
    username: root
    password: 505877
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8762/eureka/
server:
  port: 8060
#设置ribbon的负载均衡策略
PRODUCT:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
user:
  name: zahngsan
  age: 5000747457
env:
  dev
